fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: Owp\OwpCore\Entity\User
    from_email:
        address: '%env(resolve:APP_MAIL)%'
        sender_name: '%env(resolve:APP_NAME)%'
    registration:
        form:
            type: Owp\OwpCore\Form\RegistrationType
    profile:
        form:
            type: Owp\OwpCore\Form\ProfileType
