fos_comment:
    db_driver: orm
    class:
        model:
            comment: Owp\OwpCore\Entity\Comment
            thread: Owp\OwpCore\Entity\Thread
    service:
        sorting:
            default: date_asc
