sonata_admin:
    title: 'Sonata Admin'
    dashboard:
        blocks:
            - { type: sonata.block.admin_stat, position: top, class: col-md-12 }
        groups:
            content:
                label:           'Content'
                icon:            '<i class="fa fa-file fa-lg mr-2"></i>'
            referentiel:
                label:           'Datum'
                icon:            '<i class="fa fa-database fa-lg mr-2"></i>'
            user:
                label:           'Users'
                icon:            '<i class="fa fa-user fa-lg mr-2"></i>'
            parameter:
                label:           'Parameters'
                icon:            '<i class="fa fa-cog fa-lg mr-2"></i>'
    templates:
        layout:             'Administration/base_administration.html.twig'
        knp_menu_template:  'Administration/Menu/admin_menu.html.twig'
        button_create:      'Administration/Button/create_button.html.twig'

sonata_block:
    blocks:
        sonata.block.admin_stat:
            contexts: [admin]
