sonata_admin:
    title: 'Sonata Admin'
    dashboard:
        blocks:
            - { type: sonata.block.admin_stat, position: top, class: col-md-12 }
        groups:
            content:
                label:           'Content'
                icon:            '<i class="fa fa-file fa-lg mr-2"></i>'
            referentiel:
                label:           'Datum'
                icon:            '<i class="fa fa-database fa-lg mr-2"></i>'
            user:
                label:           'Users'
                icon:            '<i class="fa fa-user fa-lg mr-2"></i>'
            parameter:
                label:           'Parameters'
                icon:            '<i class="fa fa-cog fa-lg mr-2"></i>'
    templates:
        layout:             'Administration/base_administration.html.twig'
        knp_menu_template:  'Administration/Menu/admin_menu.html.twig'
        button_create:      'Administration/Button/create_button.html.twig'
    assets:
        stylesheets:
            # The default stylesheet list:
            - bundles/sonatacore/vendor/components-font-awesome/css/font-awesome.min.css
            - bundles/sonatacore/vendor/ionicons/css/ionicons.min.css
            - bundles/sonataadmin/vendor/admin-lte/dist/css/AdminLTE.min.css
            - bundles/sonataadmin/vendor/admin-lte/dist/css/skins/skin-black.min.css
            - bundles/sonataadmin/vendor/iCheck/skins/square/blue.css
            - bundles/sonatacore/vendor/eonasdan-bootstrap-datetimepicker/build/css/bootstrap-datetimepicker.min.css
            - bundles/sonataadmin/vendor/jqueryui/themes/base/jquery-ui.css
            - bundles/sonatacore/vendor/select2/select2.css
            - bundles/sonatacore/vendor/select2-bootstrap-css/select2-bootstrap.min.css
            - bundles/sonataadmin/vendor/x-editable/dist/bootstrap3-editable/css/bootstrap-editable.css
            - bundles/sonataadmin/css/styles.css
            - bundles/sonataadmin/css/layout.css
            - bundles/sonataadmin/css/tree.css
            - bundles/sonataadmin/css/colors.css
            
sonata_block:
    blocks:
        sonata.block.admin_stat:
            contexts: [admin]
