twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        app_name: '%env(resolve:APP_NAME)%'
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
        - '@SonataFormatter/Form/formatter.html.twig'
        - '@SonataCore/Form/datepicker.html.twig'
