vich_uploader:
    db_driver: orm

    mappings:
        event_file:
            uri_prefix: /files/event/
            upload_destination: '%kernel.project_dir%/public/files/events'
        content_image:
            uri_prefix: /images
            upload_destination: '%kernel.project_dir%/public/images/'
