owp_administration_administration:
    path: /admin
    defaults: { _controller: 'App\Administration\Controller\DefaultController::index' }
owp_administration_administration_content_news:
    path: /admin/news
    defaults: { _controller: 'App\Administration\Controller\NewsController::index' }
owp_administration_administration_content_news_add:
    path: /admin/news/add
    defaults: { _controller: 'App\Administration\Controller\NewsController::add' }
owp_administration_administration_content_news_edit:
    path: /admin/news/edit/{id}
    defaults: { _controller: 'App\Administration\Controller\NewsController::edit' }
owp_administration_administration_content_news_delete:
    path: /admin/news/delete/{id}
    defaults: { _controller: 'App\Administration\Controller\NewsController::delete' }
    
owp_administration_administration_users:
    path: /admin/user
    defaults: { _controller: 'App\Administration\Controller\UserController::index' }
