owp_core:
    resource: "@OwpCoreBundle/Resources/config/routes.xml"

owp_news:
    resource: "@OwpNewsBundle/Resources/config/routes.xml"

owp_event:
    resource: "@OwpEventBundle/Resources/config/routes.xml"

owp_entry:
    resource: "@OwpEntryBundle/Resources/config/routes.xml"

owp_map:
    resource: "@OwpMapBundle/Resources/config/routes.xml"
